language: python
python:
  - "3.5"
install:
  - pip install coverage==3.7.1 tox==1.9.2 virtualenv==13.1.2
script:
  - tox
  - coverage run --rcfile=.coveragerc setup.py test -s tests.unit
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    on_failure: change
sudo: false