language: python
python:
  - "3.5"
install:
  - pip install coverage tox virtualenv
  - pip install coveralls
script:
  - tox
  - coverage run --rcfile=.coveragerc setup.py test -s tests.unit
after_success:
  coveralls
notifications:
  email:
    on_failure: change
sudo: false